Repository codednepal/hacktober2022, pull requests merged in 2022-10, with the labels that each got.

#1 Add files via upload
  C-codes/mysql/mysql.c
Labels: good first issue, Hacktoberfest-accepted, Hacktoberfest2022

#4 Socket program for linux.
  C-codes/socket/client.c
  C-codes/socket/server.c
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#5 Hacktoberfest contribution
  C-codes/gussthenum/command.c
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#6 Contribution For Hacktoberfest
  C-codes/Num Converters/Dec2bin/dec2bi.c
  C-codes/Num Converters/Dex2hex/dex2hex.c
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#8 Contibution for Hacktoberfest
  Java-codes/Area/circle.java
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#10 java programs
  Java-codes/impotant Programs/FactorialofNum.java
  Java-codes/impotant Programs/checkPalindrome.java
  Java-codes/impotant Programs/checkevenodd.java
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#12 Programs
  Java-codes/impotant Programs/Concatenate.java
  Java-codes/impotant Programs/Fibonacci.java
  Java-codes/impotant Programs/swapping.java
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#14 Update README.md
  README.md
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#17 Contribution for hacktoberfest
  c++/important programs/evenodd.cpp
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#16 Added BFS program in java
  Java-codes/impotant Programs/BFS.java
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#15 Added the scheduling Algorithm in C
  C-codes/SchedulingAlgo/RoundRobin.c
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#20 Add more num converters
  C-codes/Num Converters/Bin2oct/bin2oct.c
  C-codes/Num Converters/Hex2bin/hex2bin.c
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#23 cyclically rotate an array by one
  C-codes/cyclically_rotate_an_array_by_one.c
  merge2sortedArrays.c
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#25 kadane’sAlgo.java
  Java-codes/impotant Programs/kadane’sAlgo.java
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#28 reverse_the_array.java
  Java-codes/reverse_the_array.java
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#29 huffman_Coding.java
  Java-codes/huffman_Coding.java
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#30 Create package.json
  React/portfolio/package.json
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#32 Binary_search_tree_in_java
  Java-codes/impotant Programs/Binary_search_tree_in_java.java
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#31 Create matrixadd.java
  Java-codes/matrixadd.java
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#38 Bottom view of binary tree
  Java-codes/Bottom_view_of_binary_tree.java
  Java-codes/impotant Programs/Top_view_of_binary_tree.java
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#45 Stack_implementation_in_java
  Java-codes/Stack_implementation_in.java
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#46 Bubble sort
  c++/important programs/bubble sort
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#52 Create RegularExpressionMatching.java
  Java-codes/RegularExpressionMatching.java
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#51 Create PalindromeNumber.java
  Java-codes/PalindromeNumber.java
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#50 Create StringtoInteger(atoi).java
  Java-codes/StringtoInteger(atoi).java
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#49 Create ReverseInteger.java
  Java-codes/ReverseInteger.java
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#48 Create ZigzagConversion.java
  Java-codes/ZigzagConversion.java
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#47 Create MedianofTwoSortedArrays.java
  Java-codes/MedianofTwoSortedArrays.java
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#53 Contribution for Hacktoberfest
  Java-codes/Sorting/bubblesort.java
  Java-codes/Sorting/heapsort.java
  Java-codes/Sorting/quicksort.java
  Java-codes/Sorting/selectionsort.java
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#55 #21 Problem Resolved and created Contribute.md
  README.md
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#56 📝 Created contribution for hacktoberfest
  Contribute.md
  Images/hacktoberfest.jpg
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#58 created calculator using Html and Css
  Web/calculator/index.html
  Web/calculator/style.css
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#61 simple programs
  VisualBasic/Simpleprograms/Areaofparallelogram.vb
  VisualBasic/Simpleprograms/Mathematicalcalculations.vb
  VisualBasic/Simpleprograms/typeconverison.vb
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#63 javascript file for calculator
  Web/calculator/script.js
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#64 Mycontribution
  c++/important programs/MyC++programs/Reverseanumber.cpp
  c++/important programs/MyC++programs/armstrong.cpp
  c++/important programs/MyC++programs/factorialofnumber.cpp
  c++/important programs/MyC++programs/palindrome or not.cpp
  c++/important programs/usefulprograms/GCD.cpp
  c++/important programs/usefulprograms/LCM.cpp
  c++/important programs/usefulprograms/greatestnumberinarray.cpp
  c++/important programs/usefulprograms/matrixaddition.cpp
  c++/important programs/usefulprograms/towerofhanoi.cpp
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#68 login page
  Web/loginpage/4.jpg
  Web/loginpage/loginpage.css
  Web/loginpage/loginpage.html
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#69 Added CSS for login page
  Web/loginpage/loginpage.css
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#73 Contribution for Hacktoberfest.
  C-codes/simpleinterest.c
  C-codes/sjf.c
  Java-codes/impotant Programs/calculator.java
  Java-codes/impotant Programs/prime-number.java
  c++/important programs/dijkastra.cpp
  c++/important programs/fcfs.cpp
  c++/important programs/quicksort.cpp
  c++/important programs/reverse.cpp
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#75 contribution for hacktoberfest.
  Java-codes/dijkastra.java
  Java-codes/timer.java
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#77 Create merge_sort.py
  python/merge_sort.py
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#74 rat_in_maze problem
  Java-codes/impotant Programs/rat_in_maze.java
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#78 Longest Common Subsequence
  python/lcs.py
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#80 Loading page
  Web/loading.css
  Web/loading.html
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#81 SKC group
  Web/skc group/index.html
  Web/skc group/style.css
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#83 Krukshal algorithm c++
  c++/important programs/Krukshal c++
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#89 Google login
  Google/index1.html
  Web/style1.css
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#76 kadanesAlgorithm.java
  kadanes_algorithm.java
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#82 Hosoya traingle
  c++/important programs/Hosoya traingle
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#93 Theme Changer
  Web/THEME/index.html
  Web/THEME/index.js
  Web/THEME/style.css
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#91 added shortest job first scheduling algorithm
  C-codes/SchedulingAlgo/ShortestJobFirst.c
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#108 circular_queue in python
  python/circular_queue.py
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#109 Card_game.py
  python/CardGame.py
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#107 unbounded_kanpsack.cpp
  c++/important programs/unbounded_kanpsack.cpp
Labels: good first issue, Hacktoberfest2022

#110 Painting_fence_algorithm.cpp
  c++/important programs/Painting_fence_algorithm.cpp
Labels: Hacktoberfest-accepted, Hacktoberfest2022

#113 suduko solver.c++
  c++/important programs/sudoko
Labels: Hacktoberfest-accepted, Hacktoberfest2022
